// test_bytecode.cpp - Test cases for bytecode generation
// This file tests the bytecode generation functionality

#include "Bytecode.h"
#include "CodeGenerator.h"
#include "AST.h"
#include "Lexer.h"
#include "Parser.h"
#include "SemanticAnalyzer.h"
#include <iostream>
#include <memory>
#include <string>

using namespace rglite;

// Helper function to create a simple AST from source code
std::shared_ptr<ASTNode> parseSource(const std::string& source) {
    // Create lexer
    auto lexer = std::make_shared<Lexer>();
    
    // Tokenize the source
    auto tokens = lexer->tokenize(source);
    if (lexer->hasErrors()) {
        std::cerr << "Lexer errors:" << std::endl;
        for (const auto& error : lexer->getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return nullptr;
    }
    
    // Create parser
    auto parser = std::make_shared<Parser>();
    
    // Parse the tokens
    auto ast = parser->parse(tokens);
    if (parser->hasErrors()) {
        std::cerr << "Parser errors:" << std::endl;
        for (const auto& error : parser->getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return nullptr;
    }
    
    // Create semantic analyzer
    auto analyzer = std::make_shared<SemanticAnalyzer>();
    
    // Analyze the AST
    analyzer->analyze(ast);
    if (analyzer->hasErrors()) {
        std::cerr << "Semantic analyzer errors:" << std::endl;
        for (const auto& error : analyzer->getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return nullptr;
    }
    
    return ast;
}

// Test function for simple arithmetic expression
bool testArithmeticExpression() {
    std::cout << "Testing arithmetic expression..." << std::endl;
    
    // Parse a simple arithmetic expression
    auto ast = parseSource("x = 1 + 2 * 3");
    if (!ast) {
        return false;
    }
    
    // Create code generator
    auto codegen = createCodeGenerator();
    
    // Generate bytecode
    auto function = codegen->generate(ast);
    
    // Check for errors
    if (codegen->hasErrors()) {
        std::cerr << "Code generation errors:" << std::endl;
        for (const auto& error : codegen->getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return false;
    }
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Print the instructions
    std::cout << "Generated bytecode:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
    
    return true;
}

// Test function for conditional statement
bool testConditionalStatement() {
    std::cout << "\nTesting conditional statement..." << std::endl;
    
    // Parse a simple if statement
    auto ast = parseSource("if x > 0:\n    y = x\nelse:\n    y = -x");
    if (!ast) {
        return false;
    }
    
    // Create code generator
    auto codegen = createCodeGenerator();
    
    // Generate bytecode
    auto function = codegen->generate(ast);
    
    // Check for errors
    if (codegen->hasErrors()) {
        std::cerr << "Code generation errors:" << std::endl;
        for (const auto& error : codegen->getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return false;
    }
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Print the instructions
    std::cout << "Generated bytecode:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
    
    return true;
}

// Test function for while loop
bool testWhileLoop() {
    std::cout << "\nTesting while loop..." << std::endl;
    
    // Parse a simple while loop
    auto ast = parseSource("i = 0\nwhile i < 10:\n    i = i + 1");
    if (!ast) {
        return false;
    }
    
    // Create code generator
    auto codegen = createCodeGenerator();
    
    // Generate bytecode
    auto function = codegen->generate(ast);
    
    // Check for errors
    if (codegen->hasErrors()) {
        std::cerr << "Code generation errors:" << std::endl;
        for (const auto& error : codegen->getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return false;
    }
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Print the instructions
    std::cout << "Generated bytecode:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
    
    return true;
}

// Test function for list creation
bool testListCreation() {
    std::cout << "\nTesting list creation..." << std::endl;
    
    // Parse a simple list creation
    auto ast = parseSource("x = [1, 2, 3]");
    if (!ast) {
        return false;
    }
    
    // Create code generator
    auto codegen = createCodeGenerator();
    
    // Generate bytecode
    auto function = codegen->generate(ast);
    
    // Check for errors
    if (codegen->hasErrors()) {
        std::cerr << "Code generation errors:" << std::endl;
        for (const auto& error : codegen->getErrors()) {
            std::cerr << "  " << error << std::endl;
        }
        return false;
    }
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Print the instructions
    std::cout << "Generated bytecode:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
    
    return true;
}

int main() {
    std::cout << "Running bytecode generation tests..." << std::endl;
    
    bool allPassed = true;
    
    // Run tests
    allPassed &= testArithmeticExpression();
    allPassed &= testConditionalStatement();
    allPassed &= testWhileLoop();
    allPassed &= testListCreation();
    
    // Print result
    if (allPassed) {
        std::cout << "\nAll tests passed!" << std::endl;
        return 0;
    } else {
        std::cout << "\nSome tests failed!" << std::endl;
        return 1;
    }
}