// CodeGenerator.h - Bytecode code generator for RGLite
// This file defines the code generator that converts AST to bytecode

#ifndef RGLITE_CODEGENERATOR_H
#define RGLITE_CODEGENERATOR_H

#include "AST.h"
#include "Bytecode.h"
#include <string>
#include <vector>
#include <unordered_map>
#include <memory>

namespace rglite {

// Forward declarations
class Chunk;
class Function;
class VM;

// Code generator class that converts AST to bytecode
class CodeGenerator : public ASTVisitor {
public:
    CodeGenerator();
    ~CodeGenerator() = default;
    
    // Generate bytecode from an AST node
    std::shared_ptr<Function> generate(const std::shared_ptr<ASTNode>& ast);
    
    // Get the generated bytecode chunk
    std::shared_ptr<Chunk> getBytecode() const;
    
    // Get function by index
    std::shared_ptr<Function> getFunctionByIndex(size_t index) const;
    
    // Get any errors that occurred during generation
    const std::vector<std::string>& getErrors() const { return errors_; }
    
    // Check if generation was successful
    bool hasErrors() const { return !errors_.empty(); }
    
    // Set VM instance for variable name mapping
    void setVM(VM* vm);
    
    // AST visitor methods
    void visitLiteralExpr(LiteralExpr& expr) override;
    void visitIdentifierExpr(IdentifierExpr& expr) override;
    void visitBinaryExpr(BinaryExpr& expr) override;
    void visitCallExpr(CallExpr& expr) override;
    void visitUnaryExpr(UnaryExpr& expr) override;
    void visitListExpr(ListExpr& expr) override;
    void visitDictExpr(DictExpr& expr) override;
    void visitTupleExpr(TupleExpr& expr) override;
    void visitSetExpr(SetExpr& expr) override;
    void visitMemberAccessExpr(MemberAccessExpr& expr) override;
    void visitIndexAccessExpr(IndexAccessExpr& expr) override;
    
    // Statement visitors
    void visitExprStmt(ExprStmt& stmt) override;
    void visitBlockStmt(BlockStmt& stmt) override;
    void visitIfStmt(IfStmt& stmt) override;
    void visitWhileStmt(WhileStmt& stmt) override;
    void visitForStmt(ForStmt& stmt) override;
    void visitFunctionDeclStmt(FunctionDeclStmt& stmt) override;
    void visitReturnStmt(ReturnStmt& stmt) override;
    
private:
    // Current function being generated
    std::shared_ptr<Function> currentFunction_;
    
    // All functions generated
    std::vector<std::shared_ptr<Function>> functions_;
    
    // Current chunk being written to
    Chunk* currentChunk_;
    
    // Variable tracking for scope management
    struct VariableInfo {
        size_t index;  // Index in the variable table
        bool isCaptured;  // Whether this variable is captured by a closure
    };
    
    // Map variable names to their information
    std::unordered_map<std::string, VariableInfo> variables_;
    
    // Next variable index to assign
    size_t nextVariableIndex_;
    
    // List of errors encountered during generation
    std::vector<std::string> errors_;
    
    // Emit an instruction to the current chunk
    void emitInstruction(OpCode opcode, uint32_t operand = 0);
    
    // Emit a constant to the current chunk and return its index
    size_t emitConstant(const Value& value);
    
    // Add an error message
    void error(const std::string& message, const SourceLocation& pos = SourceLocation{0, 0});
    
    // Get or create a variable index
    size_t getVariableIndex(const std::string& name);
    
    // Create a new variable
    size_t createVariable(const std::string& name);
    
    // Check if a name is a builtin function
    bool isBuiltinFunction(const std::string& name);
    
    // Generate bytecode for an expression
    void generateExpression(const std::shared_ptr<ASTNode>& expr);
    
    // Generate bytecode for a statement
    void generateStatement(const std::shared_ptr<ASTNode>& stmt);
    
    // Patch a jump instruction with the target address
    void patchJump(size_t instructionIndex);
    
    // Begin a new scope
    void beginScope();
    
    // End the current scope
    void endScope();
    
    // Current scope depth
    int scopeDepth_;
    
    // VM instance for setting variable name mappings
    VM* vm_;
};

// Factory function to create a code generator
std::shared_ptr<CodeGenerator> createCodeGenerator();

} // namespace rglite

#endif // RGLITE_CODEGENERATOR_H