// test_bytecode.cpp - Test cases for bytecode generation
// This file tests the bytecode generation functionality using Universal Test Framework

#include "Bytecode.h"
#include "CodeGenerator.h"
#include "AST.h"
#include "Lexer.h"
#include "Parser.h"
#include "SemanticAnalyzer.h"
#include "ErrorHandler.h"
#include "TestFramework.h"
#include <iostream>
#include <memory>
#include <string>
#include <sstream>

using namespace rglite;

/**
 * @brief Bytecode generation test fixture for common setup
 */
class BytecodeGenerationTestFixture : public testing::TestFixture {
protected:
    std::shared_ptr<StandardErrorHandler> errorHandler;
    std::shared_ptr<CodeGenerator> codegen;
    
    void SetUp() override {
        errorHandler = std::make_shared<StandardErrorHandler>();
        codegen = createCodeGenerator();
    }
    
    void TearDown() override {
        codegen.reset();
        errorHandler.reset();
    }
    
    /**
     * @brief Helper function to parse source code and return AST
     */
    std::unique_ptr<Stmt> parseSource(const std::string& source) {
        // Create lexer with source
        auto lexer = std::make_unique<Lexer>(source, "test.rgb", errorHandler);
        
        // Create parser with lexer
        auto parser = std::make_unique<Parser>(std::move(lexer), errorHandler);
        
        // Parse the source
        auto ast = parser->parse();
        if (errorHandler->hasErrors()) {
            std::cerr << "Parser errors:" << std::endl;
            for (const auto& error : errorHandler->getDiagnostics()) {
                std::cerr << "  " << error.toString() << std::endl;
            }
            return nullptr;
        }
        
        // Create semantic analyzer
        auto analyzer = std::make_unique<SemanticAnalyzer>(errorHandler);
        
        // Analyze the AST
        bool analysisSuccess = analyzer->analyze(ast);
        if (!analysisSuccess || errorHandler->hasErrors()) {
            std::cerr << "Semantic analyzer errors:" << std::endl;
            for (const auto& error : errorHandler->getDiagnostics()) {
                std::cerr << "  " << error.toString() << std::endl;
            }
            return nullptr;
        }
        
        return ast;
    }
};

// Test suite for arithmetic expression bytecode generation
TEST_F(BytecodeGenerationTestFixture, ArithmeticExpression, BytecodeGenerationTestFixture) {
    // Parse a simple arithmetic expression
    auto ast = parseSource("x = 1 + 2 * 3");
    if (ast == nullptr) {
        std::cerr << "Failed to parse arithmetic expression" << std::endl;
    }
    EXPECT_NE(ast, nullptr);
    
    // Generate bytecode
    auto function = codegen->generate(std::shared_ptr<ASTNode>(ast.release()));
    
    // Check for errors
    EXPECT_FALSE(codegen->hasErrors());
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Verify that bytecode was generated
    EXPECT_GT(chunk.size(), 0);
    
    // Print the instructions for debugging
    std::cout << "Generated bytecode for arithmetic expression:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
}

// Test suite for conditional statement bytecode generation
TEST_F(BytecodeGenerationTestFixture, ConditionalStatement, BytecodeGenerationTestFixture) {
    // Parse a simple if statement
    auto ast = parseSource("x = 5\nif x > 0:\n    y = x\nelse:\n    y = -x");
    EXPECT_NE(ast, nullptr);
    
    // Generate bytecode
    auto function = codegen->generate(std::shared_ptr<ASTNode>(ast.release()));
    
    // Check for errors
    EXPECT_FALSE(codegen->hasErrors());
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Verify that bytecode was generated
    EXPECT_GT(chunk.size(), 0);
    
    // Print the instructions for debugging
    std::cout << "Generated bytecode for conditional statement:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
}

// Test suite for while loop bytecode generation
TEST_F(BytecodeGenerationTestFixture, WhileLoop, BytecodeGenerationTestFixture) {
    // Parse a simple while loop
    auto ast = parseSource("x = 3\nwhile x > 0:\n    x = x - 1");
    EXPECT_NE(ast, nullptr);
    
    // Generate bytecode
    auto function = codegen->generate(std::shared_ptr<ASTNode>(ast.release()));
    
    // Check for errors
    EXPECT_FALSE(codegen->hasErrors());
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Verify that bytecode was generated
    EXPECT_GT(chunk.size(), 0);
    
    // Print the instructions for debugging
    std::cout << "Generated bytecode for while loop:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
}

// Test suite for list creation bytecode generation
TEST_F(BytecodeGenerationTestFixture, ListCreation, BytecodeGenerationTestFixture) {
    // Parse a simple list creation
    auto ast = parseSource("lst = [1, 2, 3]");
    EXPECT_NE(ast, nullptr);
    
    // Generate bytecode
    auto function = codegen->generate(std::shared_ptr<ASTNode>(ast.release()));
    
    // Check for errors
    EXPECT_FALSE(codegen->hasErrors());
    
    // Get the bytecode chunk
    const auto& chunk = function->getChunk();
    
    // Verify that bytecode was generated
    EXPECT_GT(chunk.size(), 0);
    
    // Print the instructions for debugging
    std::cout << "Generated bytecode for list creation:" << std::endl;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        std::cout << "  " << i << ": " << opCodeToString(instr.opcode);
        if (instr.operand != 0) {
            std::cout << " " << instr.operand;
        }
        std::cout << std::endl;
    }
}

// Test suite for member attribute assignment bytecode generation
TEST_F(BytecodeGenerationTestFixture, MemberAssignment, BytecodeGenerationTestFixture) {
    auto ast = parseSource("d = {}\nd.attr = 1");
    EXPECT_NE(ast, nullptr);

    auto function = codegen->generate(std::shared_ptr<ASTNode>(ast.release()));
    EXPECT_FALSE(codegen->hasErrors());
    const auto& chunk = function->getChunk();
    EXPECT_GT(chunk.size(), 0);

    bool foundSetAttr = false;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        if (instr.opcode == OpCode::SET_ATTR) {
            foundSetAttr = true;
            break;
        }
    }
    EXPECT_TRUE(foundSetAttr);
}

// Test suite for index assignment bytecode generation
TEST_F(BytecodeGenerationTestFixture, IndexAssignment, BytecodeGenerationTestFixture) {
    auto ast = parseSource("a = [0]\na[0] = 42");
    EXPECT_NE(ast, nullptr);

    auto function = codegen->generate(std::shared_ptr<ASTNode>(ast.release()));
    EXPECT_FALSE(codegen->hasErrors());
    const auto& chunk = function->getChunk();
    EXPECT_GT(chunk.size(), 0);

    bool foundSetItem = false;
    for (size_t i = 0; i < chunk.size(); ++i) {
        const auto& instr = chunk.getInstruction(i);
        if (instr.opcode == OpCode::SET_ITEM) {
            foundSetItem = true;
            break;
        }
    }
    EXPECT_TRUE(foundSetItem);
}

RUN_ALL_TESTS();
